# Generated by Django 5.0.11 on 2025-04-24 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='url_args',
            new_name='info_args',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='url_name',
        ),
    ]
