# Generated by Django 5.2.10 on 2026-04-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_url_args_notification_info_args_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_discussion', 'New discussion'), ('new_message', 'New message'), ('accepted_invite', 'Accepted invite')], max_length=32),
        ),
        migrations.DeleteModel(
            name='NotificationType',
        ),
    ]
