services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-}
