[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[fcgi-program:asgi]
socket=tcp://0.0.0.0:8000
directory=/app
command=/opt/venv/bin/daphne -u /run/daphne/daphne%(process_num)02d.sock --fd 0 --access-log - --proxy-headers ProjectOpenDebate.asgi:application
numprocs=4
process_name=asgi%(process_num)02d
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
stopasgroup=true
killasgroup=true
