# Generated by Django 5.0.11 on 2025-04-23 06:09

from django.db import migrations, models

def map_zero_to_minus_one(apps, schema_editor):
    DiscussionRequest = apps.get_model('discussion', 'DiscussionRequest')
    DiscussionRequest.objects.filter(stance_wanted=0).update(stance_wanted=-1)

class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_discussion_is_archived_for_p1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionrequest',
            name='stance_wanted',
            field=models.IntegerField(choices=[(1, 'FOR'), (-1, 'AGAINST')]),
        ),
        migrations.RunPython(map_zero_to_minus_one),
    ]
