# Generated by Django 5.0.11 on 2025-11-03 13:46

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('debate', '0007_alter_stance_stance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('vote', models.SmallIntegerField(choices=[(1, '+1'), (-1, '-1')])),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='stance',
            name='debate_stan_user_id_a1af96_idx',
        ),
        migrations.AlterField(
            model_name='stance',
            name='stance',
            field=models.SmallIntegerField(choices=[(1, 'FOR'), (-1, 'AGAINST')]),
        ),
        migrations.AddIndex(
            model_name='stance',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['debate', 'stance'], include=('id',), name='stance_debate_stance_idx'),
        ),
        migrations.AddField(
            model_name='vote',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['content_type', 'object_id'], include=('vote', 'id'), name='votes_ct_obj_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['content_type', 'object_id', 'user'], include=('vote', 'id'), name='votes_ct_obj_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'user'), name='unique_user_vote_per_object'),
        ),
    ]
