# Generated by Django 5.2.10 on 2026-03-24 05:59

import debate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0008_vote_remove_stance_debate_stan_user_id_a1af96_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=debate.models.debate_image_upload_to),
        ),
    ]
