# Generated by Django 5.2.10 on 2026-03-31 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0009_debate_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDebateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(help_text='Short review summary sent for human approval.')),
                ('cover_image_reasoning', models.TextField(blank=True, help_text='Model-provided rationale for the generated contextual cover image.')),
                ('cover_image_generation_error', models.TextField(blank=True)),
                ('cover_image_generated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('failed', 'Failed')], default='discovered', max_length=24)),
                ('source_payload', models.JSONField(blank=True, default=dict, help_text='Raw discovery metadata and source links used to generate the candidate.')),
                ('similarity_payload', models.JSONField(blank=True, default=list, help_text='Stored similarity matches against existing debates for reviewer context.')),
                ('reviewer_notes', models.TextField(blank=True)),
                ('review_requested_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-discovered_at'],
            },
        ),
        migrations.AddField(
            model_name='debate',
            name='featured_on',
            field=models.DateField(blank=True, help_text='When set, the debate is eligible for the debate-of-the-day section for that date.', null=True),
        ),
        migrations.AddField(
            model_name='debate',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='debate',
            index=models.Index(fields=['hidden'], name='debate_hidden_idx'),
        ),
        migrations.AddIndex(
            model_name='debate',
            index=models.Index(fields=['featured_on'], name='debate_featured_on_idx'),
        ),
        migrations.AddField(
            model_name='generateddebatecandidate',
            name='debate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_candidate', to='debate.debate'),
        ),
        migrations.AddIndex(
            model_name='generateddebatecandidate',
            index=models.Index(fields=['status', '-discovered_at'], name='debate_gene_status_0445b1_idx'),
        ),
    ]
