# Generated by Django 5.0.11 on 2025-05-26 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0005_alter_discussionrequest_stance_wanted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscussionRequest',
        ),
    ]
