# Generated by Django 5.0.11 on 2025-04-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_show_recent_stances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='show_recent_stances',
        ),
    ]
