# Generated by Django 5.0.11 on 2025-04-24 20:10

from django.db import migrations, models

def map_zero_to_minus_one(apps, schema_editor):
    PairingRequest = apps.get_model('pairing', 'PairingRequest')
    PairingRequest.objects.filter(desired_stance=0).update(desired_stance=-1)

class Migration(migrations.Migration):

    dependencies = [
        ('pairing', '0002_alter_pairingmatch_related_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairingrequest',
            name='desired_stance',
            field=models.IntegerField(choices=[(1, 'FOR'), (-1, 'AGAINST')]),
        ),
        migrations.RunPython(map_zero_to_minus_one),
    ]
