# Generated by Django 5.0.11 on 2025-10-21 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0007_alter_stance_stance'),
        ('pairing', '0003_alter_pairingrequest_desired_stance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairingrequest',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('passive', 'Passive'), ('match_found', 'Match Found'), ('paired', 'Paired')], max_length=25),
        ),
        migrations.AddIndex(
            model_name='pairingrequest',
            index=models.Index(condition=models.Q(('status', 'active')), fields=['debate', 'desired_stance', 'created_at', 'id'], name='idx_pairing_waiting_key'),
        ),
    ]
