name: Django Tests

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Build and run tests
        run: |
          docker compose -f docker-compose.test.yml up --build --abort-on-container-exit --exit-code-from backend
